ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACCOUNT_BLOCKED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SYSTEM';

ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "metadata" JSONB;
