export const ErrorCodes = {
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  EMAIL_VERIFICATION_REQUIRED: 'EMAIL_VERIFICATION_REQUIRED',
  STORE_LISTING_LIMIT_REACHED: 'STORE_LISTING_LIMIT_REACHED',
  STORE_LIMIT_REACHED: 'STORE_LIMIT_REACHED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  ASSISTANT_DAILY_LIMIT_REACHED: 'ASSISTANT_DAILY_LIMIT_REACHED'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
