export const ErrorCodes = {
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  EMAIL_VERIFICATION_REQUIRED: 'EMAIL_VERIFICATION_REQUIRED',
  STORE_LISTING_LIMIT_REACHED: 'STORE_LISTING_LIMIT_REACHED',
  STORE_LIMIT_REACHED: 'STORE_LIMIT_REACHED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  ASSISTANT_DAILY_LIMIT_REACHED: 'ASSISTANT_DAILY_LIMIT_REACHED',
  PAYMENT_COMING_SOON: 'PAYMENT_COMING_SOON',
  SUBSCRIPTION_RENEWAL_TOO_EARLY: 'SUBSCRIPTION_RENEWAL_TOO_EARLY',
  SUBSCRIPTION_FREE_PLAN_UPGRADE_NOT_ALLOWED: 'SUBSCRIPTION_FREE_PLAN_UPGRADE_NOT_ALLOWED',
  SUBSCRIPTION_SAME_PLAN_NOT_ALLOWED: 'SUBSCRIPTION_SAME_PLAN_NOT_ALLOWED',
  SUBSCRIPTION_DOWNGRADE_NOT_ALLOWED: 'SUBSCRIPTION_DOWNGRADE_NOT_ALLOWED',
  RESEND_COOLDOWN: 'RESEND_COOLDOWN',
  PHONE_VERIFICATION_REQUIRED: 'PHONE_VERIFICATION_REQUIRED',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  SESSION_EXPIRED: 'SESSION_EXPIRED'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
