import {
  Anchor,
  Baby,
  Bike,
  BookOpen,
  Box,
  Briefcase,
  Brush,
  Building2,
  Calculator,
  Camera,
  Car,
  Coffee,
  Compass,
  Crown,
  Dumbbell,
  Fish,
  Flower2,
  Gamepad2,
  Gavel,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HardHat,
  Headphones,
  Heart,
  Home,
  Key,
  Laptop,
  Lightbulb,
  MapPin,
  Megaphone,
  Mic,
  Monitor,
  Music,
  Package,
  Palette,
  PawPrint,
  PenLine,
  Pill,
  Plane,
  Printer,
  Recycle,
  Scissors,
  Search,
  Settings,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Sun,
  Tag,
  Tent,
  Ticket,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Users,
  Utensils,
  Video,
  Wallet,
  Watch,
  Wifi,
  Wrench,
  Zap
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const categoryIconKeys = [
  'anchor',
  'baby',
  'bag',
  'bike',
  'book',
  'box',
  'briefcase',
  'brush',
  'building',
  'calculator',
  'camera',
  'car',
  'cart',
  'coffee',
  'compass',
  'cog',
  'crown',
  'dumbbell',
  'fish',
  'flower',
  'gamepad',
  'gavel',
  'gem',
  'gift',
  'globe',
  'graduation',
  'hammer',
  'hardhat',
  'headphones',
  'heart',
  'home',
  'key',
  'laptop',
  'lightbulb',
  'map-pin',
  'megaphone',
  'mic',
  'money',
  'monitor',
  'music',
  'package',
  'palette',
  'paw',
  'pen',
  'pill',
  'plane',
  'printer',
  'recycle',
  'scissors',
  'search',
  'shield',
  'ship',
  'shirt',
  'smartphone',
  'sofa',
  'sparkles',
  'star',
  'store',
  'stethoscope',
  'sun',
  'tag',
  'tent',
  'ticket',
  'tree',
  'trophy',
  'truck',
  'tv',
  'users',
  'utensils',
  'video',
  'watch',
  'wifi',
  'wrench',
  'zap'
] as const;

export type CategoryIconKey = (typeof categoryIconKeys)[number];

export const categoryIconMap: Record<CategoryIconKey, LucideIcon> = {
  anchor: Anchor,
  baby: Baby,
  bag: ShoppingBag,
  bike: Bike,
  book: BookOpen,
  box: Box,
  briefcase: Briefcase,
  brush: Brush,
  building: Building2,
  calculator: Calculator,
  camera: Camera,
  car: Car,
  cart: ShoppingCart,
  coffee: Coffee,
  compass: Compass,
  cog: Settings,
  crown: Crown,
  dumbbell: Dumbbell,
  fish: Fish,
  flower: Flower2,
  gamepad: Gamepad2,
  gavel: Gavel,
  gem: Gem,
  gift: Gift,
  globe: Globe,
  graduation: GraduationCap,
  hammer: Hammer,
  hardhat: HardHat,
  headphones: Headphones,
  heart: Heart,
  home: Home,
  key: Key,
  laptop: Laptop,
  lightbulb: Lightbulb,
  'map-pin': MapPin,
  megaphone: Megaphone,
  mic: Mic,
  money: Wallet,
  monitor: Monitor,
  music: Music,
  package: Package,
  palette: Palette,
  paw: PawPrint,
  pen: PenLine,
  pill: Pill,
  plane: Plane,
  printer: Printer,
  recycle: Recycle,
  scissors: Scissors,
  search: Search,
  shield: Shield,
  ship: Ship,
  shirt: Shirt,
  smartphone: Smartphone,
  sofa: Sofa,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  stethoscope: Stethoscope,
  sun: Sun,
  tag: Tag,
  tent: Tent,
  ticket: Ticket,
  tree: TreePine,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  users: Users,
  utensils: Utensils,
  video: Video,
  watch: Watch,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap
};

export const categoryIconLabels: Record<CategoryIconKey, string> = {
  anchor: 'Marine',
  baby: 'Kids',
  bag: 'Shopping bag',
  bike: 'Bikes',
  book: 'Books',
  box: 'Storage',
  briefcase: 'Jobs',
  brush: 'Art',
  building: 'Real estate',
  calculator: 'Finance',
  camera: 'Cameras',
  car: 'Cars',
  cart: 'Shopping cart',
  coffee: 'Cafes',
  compass: 'Tourism',
  cog: 'Services',
  crown: 'Luxury',
  dumbbell: 'Sports',
  fish: 'Seafood',
  flower: 'Garden',
  gamepad: 'Gaming',
  gavel: 'Legal',
  gem: 'Jewelry',
  gift: 'Gifts',
  globe: 'International',
  graduation: 'Training',
  hammer: 'Construction',
  hardhat: 'Contracting',
  headphones: 'Audio',
  heart: 'Care',
  home: 'Home',
  key: 'Rentals',
  laptop: 'Computers',
  lightbulb: 'Lighting',
  'map-pin': 'Places',
  megaphone: 'Marketing',
  mic: 'Audio services',
  money: 'Money',
  monitor: 'Electronics',
  music: 'Music',
  package: 'Packages',
  palette: 'Design',
  paw: 'Pets',
  pen: 'Stationery',
  pill: 'Pharmacy',
  plane: 'Travel',
  printer: 'Printing',
  recycle: 'Used items',
  scissors: 'Beauty',
  search: 'Job seekers',
  shield: 'Security',
  ship: 'Shipping',
  shirt: 'Fashion',
  smartphone: 'Mobile',
  sofa: 'Furniture',
  sparkles: 'Cosmetics',
  star: 'Featured',
  store: 'Stores',
  stethoscope: 'Health',
  sun: 'Solar',
  tag: 'Offers',
  tent: 'Outdoor',
  ticket: 'Events',
  tree: 'Agriculture',
  trophy: 'Awards',
  truck: 'Logistics',
  tv: 'TV',
  users: 'Community',
  utensils: 'Food',
  video: 'Video',
  watch: 'Accessories',
  wifi: 'Internet',
  wrench: 'Maintenance',
  zap: 'Energy'
};

export const isCategoryIconKey = (value?: string | null): value is CategoryIconKey =>
  Boolean(value && categoryIconKeys.includes(value as CategoryIconKey));

export const isCategoryEmojiIcon = (value?: string | null) =>
  Boolean(value && !isCategoryIconKey(value) && /\p{Extended_Pictographic}/u.test(value));

type CategoryIconProps = {
  icon?: string | null;
  size?: number;
  className?: string;
  strokeWidth?: number;
};

export function CategoryIcon({ icon, size = 40, className, strokeWidth = 1.5 }: CategoryIconProps) {
  if (isCategoryEmojiIcon(icon)) {
    return (
      <span className={className} style={{ fontSize: size * 0.85, lineHeight: 1 }}>
        {icon}
      </span>
    );
  }

  const Icon = isCategoryIconKey(icon) ? categoryIconMap[icon] : Tag;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} />;
}
