export type PhoneCountry = {
  code: string;
  dialCode: string;
  nameEn: string;
  nameAr: string;
  stripLeadingZero: boolean;
};

export const DEFAULT_PHONE_COUNTRY = 'OM';

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { code: 'AF', dialCode: '93', nameEn: 'Afghanistan', nameAr: 'أفغانستان', stripLeadingZero: true },
  { code: 'AL', dialCode: '355', nameEn: 'Albania', nameAr: 'ألبانيا', stripLeadingZero: true },
  { code: 'DZ', dialCode: '213', nameEn: 'Algeria', nameAr: 'الجزائر', stripLeadingZero: true },
  { code: 'AS', dialCode: '1684', nameEn: 'American Samoa', nameAr: 'ساموا الأمريكية', stripLeadingZero: true },
  { code: 'AD', dialCode: '376', nameEn: 'Andorra', nameAr: 'أندورا', stripLeadingZero: true },
  { code: 'AO', dialCode: '244', nameEn: 'Angola', nameAr: 'أنغولا', stripLeadingZero: true },
  { code: 'AI', dialCode: '1264', nameEn: 'Anguilla', nameAr: 'أنغويلا', stripLeadingZero: true },
  { code: 'AG', dialCode: '1268', nameEn: 'Antigua and Barbuda', nameAr: 'أنتيغوا وبربودا', stripLeadingZero: true },
  { code: 'AR', dialCode: '54', nameEn: 'Argentina', nameAr: 'الأرجنتين', stripLeadingZero: true },
  { code: 'AM', dialCode: '374', nameEn: 'Armenia', nameAr: 'أرمينيا', stripLeadingZero: true },
  { code: 'AW', dialCode: '297', nameEn: 'Aruba', nameAr: 'أروبا', stripLeadingZero: true },
  { code: 'AU', dialCode: '61', nameEn: 'Australia', nameAr: 'أستراليا', stripLeadingZero: true },
  { code: 'AT', dialCode: '43', nameEn: 'Austria', nameAr: 'النمسا', stripLeadingZero: true },
  { code: 'AZ', dialCode: '994', nameEn: 'Azerbaijan', nameAr: 'أذربيجان', stripLeadingZero: true },
  { code: 'BS', dialCode: '1242', nameEn: 'Bahamas', nameAr: 'الباهاما', stripLeadingZero: true },
  { code: 'BH', dialCode: '973', nameEn: 'Bahrain', nameAr: 'البحرين', stripLeadingZero: true },
  { code: 'BD', dialCode: '880', nameEn: 'Bangladesh', nameAr: 'بنغلاديش', stripLeadingZero: true },
  { code: 'BB', dialCode: '1246', nameEn: 'Barbados', nameAr: 'بربادوس', stripLeadingZero: true },
  { code: 'BY', dialCode: '375', nameEn: 'Belarus', nameAr: 'بيلاروس', stripLeadingZero: true },
  { code: 'BE', dialCode: '32', nameEn: 'Belgium', nameAr: 'بلجيكا', stripLeadingZero: true },
  { code: 'BZ', dialCode: '501', nameEn: 'Belize', nameAr: 'بليز', stripLeadingZero: true },
  { code: 'BJ', dialCode: '229', nameEn: 'Benin', nameAr: 'بنين', stripLeadingZero: true },
  { code: 'BM', dialCode: '1441', nameEn: 'Bermuda', nameAr: 'برمودا', stripLeadingZero: true },
  { code: 'BT', dialCode: '975', nameEn: 'Bhutan', nameAr: 'بوتان', stripLeadingZero: true },
  { code: 'BO', dialCode: '591', nameEn: 'Bolivia', nameAr: 'بوليفيا', stripLeadingZero: true },
  { code: 'BA', dialCode: '387', nameEn: 'Bosnia and Herzegovina', nameAr: 'البوسنة والهرسك', stripLeadingZero: true },
  { code: 'BW', dialCode: '267', nameEn: 'Botswana', nameAr: 'بوتسوانا', stripLeadingZero: true },
  { code: 'BR', dialCode: '55', nameEn: 'Brazil', nameAr: 'البرازيل', stripLeadingZero: true },
  { code: 'IO', dialCode: '246', nameEn: 'British Indian Ocean Territory', nameAr: 'إقليم المحيط الهندي البريطاني', stripLeadingZero: true },
  { code: 'BN', dialCode: '673', nameEn: 'Brunei', nameAr: 'بروناي', stripLeadingZero: true },
  { code: 'BG', dialCode: '359', nameEn: 'Bulgaria', nameAr: 'بلغاريا', stripLeadingZero: true },
  { code: 'BF', dialCode: '226', nameEn: 'Burkina Faso', nameAr: 'بوركينا فاسو', stripLeadingZero: true },
  { code: 'BI', dialCode: '257', nameEn: 'Burundi', nameAr: 'بوروندي', stripLeadingZero: true },
  { code: 'KH', dialCode: '855', nameEn: 'Cambodia', nameAr: 'كمبوديا', stripLeadingZero: true },
  { code: 'CM', dialCode: '237', nameEn: 'Cameroon', nameAr: 'الكاميرون', stripLeadingZero: true },
  { code: 'CA', dialCode: '1', nameEn: 'Canada', nameAr: 'كندا', stripLeadingZero: false },
  { code: 'CV', dialCode: '238', nameEn: 'Cape Verde', nameAr: 'الرأس الأخضر', stripLeadingZero: true },
  { code: 'KY', dialCode: '1345', nameEn: 'Cayman Islands', nameAr: 'جزر كايمان', stripLeadingZero: true },
  { code: 'CF', dialCode: '236', nameEn: 'Central African Republic', nameAr: 'جمهورية أفريقيا الوسطى', stripLeadingZero: true },
  { code: 'TD', dialCode: '235', nameEn: 'Chad', nameAr: 'تشاد', stripLeadingZero: true },
  { code: 'CL', dialCode: '56', nameEn: 'Chile', nameAr: 'تشيلي', stripLeadingZero: true },
  { code: 'CN', dialCode: '86', nameEn: 'China', nameAr: 'الصين', stripLeadingZero: true },
  { code: 'CX', dialCode: '61', nameEn: 'Christmas Island', nameAr: 'جزيرة كريسماس', stripLeadingZero: true },
  { code: 'CC', dialCode: '61', nameEn: 'Cocos Islands', nameAr: 'جزر كوكوس', stripLeadingZero: true },
  { code: 'CO', dialCode: '57', nameEn: 'Colombia', nameAr: 'كولومبيا', stripLeadingZero: true },
  { code: 'KM', dialCode: '269', nameEn: 'Comoros', nameAr: 'جزر القمر', stripLeadingZero: true },
  { code: 'CG', dialCode: '242', nameEn: 'Congo', nameAr: 'الكونغو', stripLeadingZero: true },
  { code: 'CD', dialCode: '243', nameEn: 'DR Congo', nameAr: 'الكونغو الديمقراطية', stripLeadingZero: true },
  { code: 'CK', dialCode: '682', nameEn: 'Cook Islands', nameAr: 'جزر كوك', stripLeadingZero: true },
  { code: 'CR', dialCode: '506', nameEn: 'Costa Rica', nameAr: 'كوستاريكا', stripLeadingZero: true },
  { code: 'CI', dialCode: '225', nameEn: 'Ivory Coast', nameAr: 'ساحل العاج', stripLeadingZero: true },
  { code: 'HR', dialCode: '385', nameEn: 'Croatia', nameAr: 'كرواتيا', stripLeadingZero: true },
  { code: 'CU', dialCode: '53', nameEn: 'Cuba', nameAr: 'كوبا', stripLeadingZero: true },
  { code: 'CY', dialCode: '357', nameEn: 'Cyprus', nameAr: 'قبرص', stripLeadingZero: true },
  { code: 'CZ', dialCode: '420', nameEn: 'Czechia', nameAr: 'التشيك', stripLeadingZero: true },
  { code: 'DK', dialCode: '45', nameEn: 'Denmark', nameAr: 'الدنمارك', stripLeadingZero: true },
  { code: 'DJ', dialCode: '253', nameEn: 'Djibouti', nameAr: 'جيبوتي', stripLeadingZero: true },
  { code: 'DM', dialCode: '1767', nameEn: 'Dominica', nameAr: 'دومينيكا', stripLeadingZero: true },
  { code: 'DO', dialCode: '1809', nameEn: 'Dominican Republic', nameAr: 'الدومينيكان', stripLeadingZero: true },
  { code: 'EC', dialCode: '593', nameEn: 'Ecuador', nameAr: 'الإكوادور', stripLeadingZero: true },
  { code: 'EG', dialCode: '20', nameEn: 'Egypt', nameAr: 'مصر', stripLeadingZero: true },
  { code: 'SV', dialCode: '503', nameEn: 'El Salvador', nameAr: 'السلفادور', stripLeadingZero: true },
  { code: 'GQ', dialCode: '240', nameEn: 'Equatorial Guinea', nameAr: 'غينيا الاستوائية', stripLeadingZero: true },
  { code: 'ER', dialCode: '291', nameEn: 'Eritrea', nameAr: 'إريتريا', stripLeadingZero: true },
  { code: 'EE', dialCode: '372', nameEn: 'Estonia', nameAr: 'إستونيا', stripLeadingZero: true },
  { code: 'SZ', dialCode: '268', nameEn: 'Eswatini', nameAr: 'إسواتيني', stripLeadingZero: true },
  { code: 'ET', dialCode: '251', nameEn: 'Ethiopia', nameAr: 'إثيوبيا', stripLeadingZero: true },
  { code: 'FK', dialCode: '500', nameEn: 'Falkland Islands', nameAr: 'جزر فوكلاند', stripLeadingZero: true },
  { code: 'FO', dialCode: '298', nameEn: 'Faroe Islands', nameAr: 'جزر فارو', stripLeadingZero: true },
  { code: 'FJ', dialCode: '679', nameEn: 'Fiji', nameAr: 'فيجي', stripLeadingZero: true },
  { code: 'FI', dialCode: '358', nameEn: 'Finland', nameAr: 'فنلندا', stripLeadingZero: true },
  { code: 'FR', dialCode: '33', nameEn: 'France', nameAr: 'فرنسا', stripLeadingZero: true },
  { code: 'GF', dialCode: '594', nameEn: 'French Guiana', nameAr: 'غويانا الفرنسية', stripLeadingZero: true },
  { code: 'PF', dialCode: '689', nameEn: 'French Polynesia', nameAr: 'بولينيزيا الفرنسية', stripLeadingZero: true },
  { code: 'GA', dialCode: '241', nameEn: 'Gabon', nameAr: 'الغابون', stripLeadingZero: true },
  { code: 'GM', dialCode: '220', nameEn: 'Gambia', nameAr: 'غامبيا', stripLeadingZero: true },
  { code: 'GE', dialCode: '995', nameEn: 'Georgia', nameAr: 'جورجيا', stripLeadingZero: true },
  { code: 'DE', dialCode: '49', nameEn: 'Germany', nameAr: 'ألمانيا', stripLeadingZero: true },
  { code: 'GH', dialCode: '233', nameEn: 'Ghana', nameAr: 'غانا', stripLeadingZero: true },
  { code: 'GI', dialCode: '350', nameEn: 'Gibraltar', nameAr: 'جبل طارق', stripLeadingZero: true },
  { code: 'GR', dialCode: '30', nameEn: 'Greece', nameAr: 'اليونان', stripLeadingZero: true },
  { code: 'GL', dialCode: '299', nameEn: 'Greenland', nameAr: 'غرينلاند', stripLeadingZero: true },
  { code: 'GD', dialCode: '1473', nameEn: 'Grenada', nameAr: 'غرينادا', stripLeadingZero: true },
  { code: 'GP', dialCode: '590', nameEn: 'Guadeloupe', nameAr: 'غوادلوب', stripLeadingZero: true },
  { code: 'GU', dialCode: '1671', nameEn: 'Guam', nameAr: 'غوام', stripLeadingZero: true },
  { code: 'GT', dialCode: '502', nameEn: 'Guatemala', nameAr: 'غواتيمالا', stripLeadingZero: true },
  { code: 'GN', dialCode: '224', nameEn: 'Guinea', nameAr: 'غينيا', stripLeadingZero: true },
  { code: 'GW', dialCode: '245', nameEn: 'Guinea-Bissau', nameAr: 'غينيا بيساو', stripLeadingZero: true },
  { code: 'GY', dialCode: '592', nameEn: 'Guyana', nameAr: 'غيانا', stripLeadingZero: true },
  { code: 'HT', dialCode: '509', nameEn: 'Haiti', nameAr: 'هايتي', stripLeadingZero: true },
  { code: 'HN', dialCode: '504', nameEn: 'Honduras', nameAr: 'هندوراس', stripLeadingZero: true },
  { code: 'HK', dialCode: '852', nameEn: 'Hong Kong', nameAr: 'هونغ كونغ', stripLeadingZero: true },
  { code: 'HU', dialCode: '36', nameEn: 'Hungary', nameAr: 'المجر', stripLeadingZero: true },
  { code: 'IS', dialCode: '354', nameEn: 'Iceland', nameAr: 'آيسلندا', stripLeadingZero: true },
  { code: 'IN', dialCode: '91', nameEn: 'India', nameAr: 'الهند', stripLeadingZero: true },
  { code: 'ID', dialCode: '62', nameEn: 'Indonesia', nameAr: 'إندونيسيا', stripLeadingZero: true },
  { code: 'IR', dialCode: '98', nameEn: 'Iran', nameAr: 'إيران', stripLeadingZero: true },
  { code: 'IQ', dialCode: '964', nameEn: 'Iraq', nameAr: 'العراق', stripLeadingZero: true },
  { code: 'IE', dialCode: '353', nameEn: 'Ireland', nameAr: 'أيرلندا', stripLeadingZero: true },
  { code: 'IL', dialCode: '972', nameEn: 'Israel', nameAr: 'إسرائيل', stripLeadingZero: true },
  { code: 'IT', dialCode: '39', nameEn: 'Italy', nameAr: 'إيطاليا', stripLeadingZero: true },
  { code: 'JM', dialCode: '1876', nameEn: 'Jamaica', nameAr: 'جامايكا', stripLeadingZero: true },
  { code: 'JP', dialCode: '81', nameEn: 'Japan', nameAr: 'اليابان', stripLeadingZero: true },
  { code: 'JO', dialCode: '962', nameEn: 'Jordan', nameAr: 'الأردن', stripLeadingZero: true },
  { code: 'KZ', dialCode: '7', nameEn: 'Kazakhstan', nameAr: 'كازاخستان', stripLeadingZero: false },
  { code: 'KE', dialCode: '254', nameEn: 'Kenya', nameAr: 'كينيا', stripLeadingZero: true },
  { code: 'KI', dialCode: '686', nameEn: 'Kiribati', nameAr: 'كيريباتي', stripLeadingZero: true },
  { code: 'KP', dialCode: '850', nameEn: 'North Korea', nameAr: 'كوريا الشمالية', stripLeadingZero: true },
  { code: 'KR', dialCode: '82', nameEn: 'South Korea', nameAr: 'كوريا الجنوبية', stripLeadingZero: true },
  { code: 'KW', dialCode: '965', nameEn: 'Kuwait', nameAr: 'الكويت', stripLeadingZero: true },
  { code: 'KG', dialCode: '996', nameEn: 'Kyrgyzstan', nameAr: 'قيرغيزستان', stripLeadingZero: true },
  { code: 'LA', dialCode: '856', nameEn: 'Laos', nameAr: 'لاوس', stripLeadingZero: true },
  { code: 'LV', dialCode: '371', nameEn: 'Latvia', nameAr: 'لاتفيا', stripLeadingZero: true },
  { code: 'LB', dialCode: '961', nameEn: 'Lebanon', nameAr: 'لبنان', stripLeadingZero: true },
  { code: 'LS', dialCode: '266', nameEn: 'Lesotho', nameAr: 'ليسوتو', stripLeadingZero: true },
  { code: 'LR', dialCode: '231', nameEn: 'Liberia', nameAr: 'ليبيريا', stripLeadingZero: true },
  { code: 'LY', dialCode: '218', nameEn: 'Libya', nameAr: 'ليبيا', stripLeadingZero: true },
  { code: 'LI', dialCode: '423', nameEn: 'Liechtenstein', nameAr: 'ليختنشتاين', stripLeadingZero: true },
  { code: 'LT', dialCode: '370', nameEn: 'Lithuania', nameAr: 'ليتوانيا', stripLeadingZero: true },
  { code: 'LU', dialCode: '352', nameEn: 'Luxembourg', nameAr: 'لوكسمبورغ', stripLeadingZero: true },
  { code: 'MO', dialCode: '853', nameEn: 'Macau', nameAr: 'ماكاو', stripLeadingZero: true },
  { code: 'MK', dialCode: '389', nameEn: 'North Macedonia', nameAr: 'مقدونيا الشمالية', stripLeadingZero: true },
  { code: 'MG', dialCode: '261', nameEn: 'Madagascar', nameAr: 'مدغشقر', stripLeadingZero: true },
  { code: 'MW', dialCode: '265', nameEn: 'Malawi', nameAr: 'مالاوي', stripLeadingZero: true },
  { code: 'MY', dialCode: '60', nameEn: 'Malaysia', nameAr: 'ماليزيا', stripLeadingZero: true },
  { code: 'MV', dialCode: '960', nameEn: 'Maldives', nameAr: 'المالديف', stripLeadingZero: true },
  { code: 'ML', dialCode: '223', nameEn: 'Mali', nameAr: 'مالي', stripLeadingZero: true },
  { code: 'MT', dialCode: '356', nameEn: 'Malta', nameAr: 'مالطا', stripLeadingZero: true },
  { code: 'MH', dialCode: '692', nameEn: 'Marshall Islands', nameAr: 'جزر مارشال', stripLeadingZero: true },
  { code: 'MQ', dialCode: '596', nameEn: 'Martinique', nameAr: 'مارتينيك', stripLeadingZero: true },
  { code: 'MR', dialCode: '222', nameEn: 'Mauritania', nameAr: 'موريتانيا', stripLeadingZero: true },
  { code: 'MU', dialCode: '230', nameEn: 'Mauritius', nameAr: 'موريشيوس', stripLeadingZero: true },
  { code: 'YT', dialCode: '262', nameEn: 'Mayotte', nameAr: 'مايوت', stripLeadingZero: true },
  { code: 'MX', dialCode: '52', nameEn: 'Mexico', nameAr: 'المكسيك', stripLeadingZero: true },
  { code: 'FM', dialCode: '691', nameEn: 'Micronesia', nameAr: 'ميكرونيزيا', stripLeadingZero: true },
  { code: 'MD', dialCode: '373', nameEn: 'Moldova', nameAr: 'مولدوفا', stripLeadingZero: true },
  { code: 'MC', dialCode: '377', nameEn: 'Monaco', nameAr: 'موناكو', stripLeadingZero: true },
  { code: 'MN', dialCode: '976', nameEn: 'Mongolia', nameAr: 'منغوليا', stripLeadingZero: true },
  { code: 'ME', dialCode: '382', nameEn: 'Montenegro', nameAr: 'الجبل الأسود', stripLeadingZero: true },
  { code: 'MS', dialCode: '1664', nameEn: 'Montserrat', nameAr: 'مونتسرات', stripLeadingZero: true },
  { code: 'MA', dialCode: '212', nameEn: 'Morocco', nameAr: 'المغرب', stripLeadingZero: true },
  { code: 'MZ', dialCode: '258', nameEn: 'Mozambique', nameAr: 'موزمبيق', stripLeadingZero: true },
  { code: 'MM', dialCode: '95', nameEn: 'Myanmar', nameAr: 'ميانمار', stripLeadingZero: true },
  { code: 'NA', dialCode: '264', nameEn: 'Namibia', nameAr: 'ناميبيا', stripLeadingZero: true },
  { code: 'NR', dialCode: '674', nameEn: 'Nauru', nameAr: 'ناورو', stripLeadingZero: true },
  { code: 'NP', dialCode: '977', nameEn: 'Nepal', nameAr: 'نيبال', stripLeadingZero: true },
  { code: 'NL', dialCode: '31', nameEn: 'Netherlands', nameAr: 'هولندا', stripLeadingZero: true },
  { code: 'NC', dialCode: '687', nameEn: 'New Caledonia', nameAr: 'كاليدونيا الجديدة', stripLeadingZero: true },
  { code: 'NZ', dialCode: '64', nameEn: 'New Zealand', nameAr: 'نيوزيلندا', stripLeadingZero: true },
  { code: 'NI', dialCode: '505', nameEn: 'Nicaragua', nameAr: 'نيكاراغوا', stripLeadingZero: true },
  { code: 'NE', dialCode: '227', nameEn: 'Niger', nameAr: 'النيجر', stripLeadingZero: true },
  { code: 'NG', dialCode: '234', nameEn: 'Nigeria', nameAr: 'نيجيريا', stripLeadingZero: true },
  { code: 'NU', dialCode: '683', nameEn: 'Niue', nameAr: 'نيوي', stripLeadingZero: true },
  { code: 'NF', dialCode: '672', nameEn: 'Norfolk Island', nameAr: 'جزيرة نورفولك', stripLeadingZero: true },
  { code: 'MP', dialCode: '1670', nameEn: 'Northern Mariana Islands', nameAr: 'جزر ماريانا الشمالية', stripLeadingZero: true },
  { code: 'NO', dialCode: '47', nameEn: 'Norway', nameAr: 'النرويج', stripLeadingZero: true },
  { code: 'OM', dialCode: '968', nameEn: 'Oman', nameAr: 'عُمان', stripLeadingZero: true },
  { code: 'PK', dialCode: '92', nameEn: 'Pakistan', nameAr: 'باكستان', stripLeadingZero: true },
  { code: 'PW', dialCode: '680', nameEn: 'Palau', nameAr: 'بالاو', stripLeadingZero: true },
  { code: 'PS', dialCode: '970', nameEn: 'Palestine', nameAr: 'فلسطين', stripLeadingZero: true },
  { code: 'PA', dialCode: '507', nameEn: 'Panama', nameAr: 'بنما', stripLeadingZero: true },
  { code: 'PG', dialCode: '675', nameEn: 'Papua New Guinea', nameAr: 'بابوا غينيا الجديدة', stripLeadingZero: true },
  { code: 'PY', dialCode: '595', nameEn: 'Paraguay', nameAr: 'باراغواي', stripLeadingZero: true },
  { code: 'PE', dialCode: '51', nameEn: 'Peru', nameAr: 'بيرو', stripLeadingZero: true },
  { code: 'PH', dialCode: '63', nameEn: 'Philippines', nameAr: 'الفلبين', stripLeadingZero: true },
  { code: 'PN', dialCode: '64', nameEn: 'Pitcairn Islands', nameAr: 'جزر بيتكايرن', stripLeadingZero: true },
  { code: 'PL', dialCode: '48', nameEn: 'Poland', nameAr: 'بولندا', stripLeadingZero: true },
  { code: 'PT', dialCode: '351', nameEn: 'Portugal', nameAr: 'البرتغال', stripLeadingZero: true },
  { code: 'PR', dialCode: '1787', nameEn: 'Puerto Rico', nameAr: 'بورتوريكو', stripLeadingZero: true },
  { code: 'QA', dialCode: '974', nameEn: 'Qatar', nameAr: 'قطر', stripLeadingZero: true },
  { code: 'RE', dialCode: '262', nameEn: 'Reunion', nameAr: 'ريونيون', stripLeadingZero: true },
  { code: 'RO', dialCode: '40', nameEn: 'Romania', nameAr: 'رومانيا', stripLeadingZero: true },
  { code: 'RU', dialCode: '7', nameEn: 'Russia', nameAr: 'روسيا', stripLeadingZero: false },
  { code: 'RW', dialCode: '250', nameEn: 'Rwanda', nameAr: 'رواندا', stripLeadingZero: true },
  { code: 'BL', dialCode: '590', nameEn: 'Saint Barthelemy', nameAr: 'سان بارتيلمي', stripLeadingZero: true },
  { code: 'SH', dialCode: '290', nameEn: 'Saint Helena', nameAr: 'سانت هيلينا', stripLeadingZero: true },
  { code: 'KN', dialCode: '1869', nameEn: 'Saint Kitts and Nevis', nameAr: 'سانت كيتس ونيفيس', stripLeadingZero: true },
  { code: 'LC', dialCode: '1758', nameEn: 'Saint Lucia', nameAr: 'سانت لوسيا', stripLeadingZero: true },
  { code: 'MF', dialCode: '590', nameEn: 'Saint Martin', nameAr: 'سان مارتين', stripLeadingZero: true },
  { code: 'PM', dialCode: '508', nameEn: 'Saint Pierre and Miquelon', nameAr: 'سان بيير وميكلون', stripLeadingZero: true },
  { code: 'VC', dialCode: '1784', nameEn: 'Saint Vincent and the Grenadines', nameAr: 'سانت فنسنت والغرينادين', stripLeadingZero: true },
  { code: 'WS', dialCode: '685', nameEn: 'Samoa', nameAr: 'ساموا', stripLeadingZero: true },
  { code: 'SM', dialCode: '378', nameEn: 'San Marino', nameAr: 'سان مارينو', stripLeadingZero: true },
  { code: 'ST', dialCode: '239', nameEn: 'Sao Tome and Principe', nameAr: 'ساو تومي وبرينسيبي', stripLeadingZero: true },
  { code: 'SA', dialCode: '966', nameEn: 'Saudi Arabia', nameAr: 'السعودية', stripLeadingZero: true },
  { code: 'SN', dialCode: '221', nameEn: 'Senegal', nameAr: 'السنغال', stripLeadingZero: true },
  { code: 'RS', dialCode: '381', nameEn: 'Serbia', nameAr: 'صربيا', stripLeadingZero: true },
  { code: 'SC', dialCode: '248', nameEn: 'Seychelles', nameAr: 'سيشل', stripLeadingZero: true },
  { code: 'SL', dialCode: '232', nameEn: 'Sierra Leone', nameAr: 'سيراليون', stripLeadingZero: true },
  { code: 'SG', dialCode: '65', nameEn: 'Singapore', nameAr: 'سنغافورة', stripLeadingZero: true },
  { code: 'SX', dialCode: '1721', nameEn: 'Sint Maarten', nameAr: 'سينت مارتن', stripLeadingZero: true },
  { code: 'SK', dialCode: '421', nameEn: 'Slovakia', nameAr: 'سلوفاكيا', stripLeadingZero: true },
  { code: 'SI', dialCode: '386', nameEn: 'Slovenia', nameAr: 'سلوفينيا', stripLeadingZero: true },
  { code: 'SB', dialCode: '677', nameEn: 'Solomon Islands', nameAr: 'جزر سليمان', stripLeadingZero: true },
  { code: 'SO', dialCode: '252', nameEn: 'Somalia', nameAr: 'الصومال', stripLeadingZero: true },
  { code: 'ZA', dialCode: '27', nameEn: 'South Africa', nameAr: 'جنوب أفريقيا', stripLeadingZero: true },
  { code: 'SS', dialCode: '211', nameEn: 'South Sudan', nameAr: 'جنوب السودان', stripLeadingZero: true },
  { code: 'ES', dialCode: '34', nameEn: 'Spain', nameAr: 'إسبانيا', stripLeadingZero: true },
  { code: 'LK', dialCode: '94', nameEn: 'Sri Lanka', nameAr: 'سريلانكا', stripLeadingZero: true },
  { code: 'SD', dialCode: '249', nameEn: 'Sudan', nameAr: 'السودان', stripLeadingZero: true },
  { code: 'SR', dialCode: '597', nameEn: 'Suriname', nameAr: 'سورينام', stripLeadingZero: true },
  { code: 'SE', dialCode: '46', nameEn: 'Sweden', nameAr: 'السويد', stripLeadingZero: true },
  { code: 'CH', dialCode: '41', nameEn: 'Switzerland', nameAr: 'سويسرا', stripLeadingZero: true },
  { code: 'SY', dialCode: '963', nameEn: 'Syria', nameAr: 'سوريا', stripLeadingZero: true },
  { code: 'TW', dialCode: '886', nameEn: 'Taiwan', nameAr: 'تايوان', stripLeadingZero: true },
  { code: 'TJ', dialCode: '992', nameEn: 'Tajikistan', nameAr: 'طاجيكستان', stripLeadingZero: true },
  { code: 'TZ', dialCode: '255', nameEn: 'Tanzania', nameAr: 'تنزانيا', stripLeadingZero: true },
  { code: 'TH', dialCode: '66', nameEn: 'Thailand', nameAr: 'تايلاند', stripLeadingZero: true },
  { code: 'TL', dialCode: '670', nameEn: 'Timor-Leste', nameAr: 'تيمور الشرقية', stripLeadingZero: true },
  { code: 'TG', dialCode: '228', nameEn: 'Togo', nameAr: 'توغو', stripLeadingZero: true },
  { code: 'TK', dialCode: '690', nameEn: 'Tokelau', nameAr: 'توكيلاو', stripLeadingZero: true },
  { code: 'TO', dialCode: '676', nameEn: 'Tonga', nameAr: 'تونغا', stripLeadingZero: true },
  { code: 'TT', dialCode: '1868', nameEn: 'Trinidad and Tobago', nameAr: 'ترينيداد وتوباغو', stripLeadingZero: true },
  { code: 'TN', dialCode: '216', nameEn: 'Tunisia', nameAr: 'تونس', stripLeadingZero: true },
  { code: 'TR', dialCode: '90', nameEn: 'Turkey', nameAr: 'تركيا', stripLeadingZero: true },
  { code: 'TM', dialCode: '993', nameEn: 'Turkmenistan', nameAr: 'تركمانستان', stripLeadingZero: true },
  { code: 'TC', dialCode: '1649', nameEn: 'Turks and Caicos Islands', nameAr: 'جزر توركس وكايكوس', stripLeadingZero: true },
  { code: 'TV', dialCode: '688', nameEn: 'Tuvalu', nameAr: 'توفالو', stripLeadingZero: true },
  { code: 'UG', dialCode: '256', nameEn: 'Uganda', nameAr: 'أوغندا', stripLeadingZero: true },
  { code: 'UA', dialCode: '380', nameEn: 'Ukraine', nameAr: 'أوكرانيا', stripLeadingZero: true },
  { code: 'AE', dialCode: '971', nameEn: 'United Arab Emirates', nameAr: 'الإمارات', stripLeadingZero: true },
  { code: 'GB', dialCode: '44', nameEn: 'United Kingdom', nameAr: 'المملكة المتحدة', stripLeadingZero: true },
  { code: 'US', dialCode: '1', nameEn: 'United States', nameAr: 'الولايات المتحدة', stripLeadingZero: false },
  { code: 'UY', dialCode: '598', nameEn: 'Uruguay', nameAr: 'أوروغواي', stripLeadingZero: true },
  { code: 'UZ', dialCode: '998', nameEn: 'Uzbekistan', nameAr: 'أوزبكستان', stripLeadingZero: true },
  { code: 'VU', dialCode: '678', nameEn: 'Vanuatu', nameAr: 'فانواتو', stripLeadingZero: true },
  { code: 'VA', dialCode: '39', nameEn: 'Vatican City', nameAr: 'الفاتيكان', stripLeadingZero: true },
  { code: 'VE', dialCode: '58', nameEn: 'Venezuela', nameAr: 'فنزويلا', stripLeadingZero: true },
  { code: 'VN', dialCode: '84', nameEn: 'Vietnam', nameAr: 'فيتنام', stripLeadingZero: true },
  { code: 'VG', dialCode: '1284', nameEn: 'British Virgin Islands', nameAr: 'جزر العذراء البريطانية', stripLeadingZero: true },
  { code: 'VI', dialCode: '1340', nameEn: 'US Virgin Islands', nameAr: 'جزر العذراء الأمريكية', stripLeadingZero: true },
  { code: 'WF', dialCode: '681', nameEn: 'Wallis and Futuna', nameAr: 'واليس وفوتونا', stripLeadingZero: true },
  { code: 'EH', dialCode: '212', nameEn: 'Western Sahara', nameAr: 'الصحراء الغربية', stripLeadingZero: true },
  { code: 'YE', dialCode: '967', nameEn: 'Yemen', nameAr: 'اليمن', stripLeadingZero: true },
  { code: 'ZM', dialCode: '260', nameEn: 'Zambia', nameAr: 'زامبيا', stripLeadingZero: true },
  { code: 'ZW', dialCode: '263', nameEn: 'Zimbabwe', nameAr: 'زيمبابوي', stripLeadingZero: true },
  { code: 'XK', dialCode: '383', nameEn: 'Kosovo', nameAr: 'كوسوفو', stripLeadingZero: true },
];
